.Dd December 1, 2024
.Dt UNHTML 1
.Os
.Sh NAME
.Nm unhtml
.Nd Strip HTML markup from a document and output UTF-8 plain text
.Sh SYNOPSIS
.Nm
.Fl help
.Nm
.Fl version
.Nm
.Op Fl comment
.Op Fl cdata Ar text | comment
.Op Fl parser Ar html | xml | tagsoup
.Op Fl verbose
.Op Ar FILENAME.html
.Sh DESCRIPTION
The
.Nm
utility removes HTML markup from a document and outputs plain text on stdout
in the UTF-8 charset.
.Pp
.Nm
is an extractor not a renderer; other tools are more appropriate if the output
is to be embellished with rendering based on HTML markup.
.Pp
Content within the
.Ql <SCRIPT>
and
.Ql <STYLE>
elements is ignored.
.Ss Options
The options are as follows:
.Bl -tag -width Ds
.It Fl version
Show the version information.
.It Fl help
Show usage and other information including the list of available parsers.
.It Fl comment
Include comments in the output.
.It Fl cdata=comment
Treat CDATA sections as comments. The default is to treat CDATA sections
simply as text that is immune from being interpreted as special HTML
sequences.
.It Fl parser
Choose between the parser types for which support is compiled in.
If a parse is not specified,
.Nm
first tries to determine the correct choice from the content of the file and
falls back to the classic HTML parser.
.It Fl verbose
Output verbose logging information on stderr.
.El
.Sh EXAMPLES
Convert
.Ql index.html
to text on stdout.
.Dl unhtml index.html
.Pp
Convert XHTML on stdin into text on stdout.
.Dl unhtml -parser xml < index.xhtml
.Sh SEE ALSO
.Xr w3m 1
.Sh HISTORY
.Nm
version 3 is a complete rewrite that is backwards-compatible with
.Nm
version 2.3.9
.Po
originally known as
.Nm clean
.Pc
written by Kevin Swan in 1998.
.Pp
The new version uses
.Lb libxml2
or
.Lb libgumbo
to parse the HTML before extracting the text. This upgrades the character
set handling from ISO-8859-1 only to UTF-8 and improves support for
different dialects of HTML in use since the original version.
.Sh AUTHORS
.An -nosplit
.An Andrew Bower Aq Mt andrew@bower.uk
.Sh BUGS
.Nm
only outputs UTF-8 and does not convert its output to the character set of
the current locale, if different.
.Pp
With the gumbo parser,
.Nm
ignores the charset defined within a
.Ql <META>
element or XML header and treats the input as UTF-8 regardless.
.Pp
Please raise bug reports at:
.Lk https://github.com/andy-bower/unhtml3/issues
